print ("Welcome to Bill Calculator for Restaurants!!")    
print ("Please enter the bill amount in INR")
bill = float (input())
print ("Please enter the tip in percentage (10 or 12 or 15 or 20)")
tip = float (input())
tip_in_percent = float ((tip/100)*bill)
total_bill = float (bill+tip_in_percent)
print ("Your total bill amount in INR", total_bill)
print ("How many people ate?")
people = int (input())
pay_each = float (total_bill/people)
rounded_pay = round (pay_each,2)
print ("Each person needs to pay INR",rounded_pay)
